"""
This file contains various constants in use by yap-midi.
"""

MAX_INT_VALUE = 128

# -----------------------
#  MIDI Event Constants:
# -----------------------

# --== Channel Messages: ==--

NOTE_ON = 0x90
NOTE_OFF = 0x80
POLY_AFTERTOUCH = 0xA0
PROGRAM_CHANGE = 0xC0
AFTER_TOUCH = 0xD0
PITCH_BEND = 0xE0
CONTROL_CHANGE = 0xB0

# Tuple of channel messages:

CHANNELS = (NOTE_ON, NOTE_OFF, POLY_AFTERTOUCH, PROGRAM_CHANGE, AFTER_TOUCH, PITCH_BEND, CONTROL_CHANGE)

# --== Real Time Messages: ==--

TIMING_CLOCK = 0xF8
START_SEQUENCE = 0xFA
CONTINUE_SEQUENCE = 0xFB
STOP_SEQUENCE = 0xFC
ACTIVE_SENSING = 0xFE
SYSTEM_RESET = 0xFF

REALTIME = (TIMING_CLOCK, START_SEQUENCE, CONTINUE_SEQUENCE, STOP_SEQUENCE, ACTIVE_SENSING, SYSTEM_RESET)

# --== System Exclusive Events: ==--

SYSTEM_EXCLUSIVE = 0xF0

EXCLUSIVE = (SYSTEM_EXCLUSIVE)

# --== System Common: ==--

SONG_POSITION_POINTER = 0xF2
SONG_SELECT = 0xF2
TUNE_REQUEST = 0xF6
EOX = 0xF7

SYSTEM_COMMON = (SONG_POSITION_POINTER, SONG_SELECT, TUNE_REQUEST, EOX)

# --== Meta Events: ==--

META = 0xFF

# Meta event types:

SEQUENCE_NUMBER = 0x00
TEXT = 0x01
COPYRIGHT = 0x02
TRACK_NAME = 0x03
INSTRUMENT = 0x04
LYRIC = 0x05
MARKER = 0x06
CUE_POINT = 0x07
CHANNEL_PREFIX = 0x20
TRACK_END = 0x2F
TEMPO_SET = 0x51
SMPTE_OFFSET = 0x54
TIME_SIGNATURE = 0x58
KEY_SIGNATURE = 0x59
RESERVED = 0x7F

META_TYPES = (SEQUENCE_NUMBER, TEXT, COPYRIGHT, TRACK_NAME, INSTRUMENT,
               LYRIC, MARKER, CUE_POINT, CHANNEL_PREFIX, TRACK_END, TEMPO_SET, 
               SMPTE_OFFSET, TIME_SIGNATURE, KEY_SIGNATURE, RESERVED)
