"""
This file contains various constants in use by yap-midi.
"""

MAX_INT_VALUE = 128

# -----------------------
#  MIDI Event Constants:
# -----------------------

# --== Channel Messages: ==--

NOTE_ON = 0x90
NOTE_OFF = 0x80
POLY_AFTERTOUCH = 0xA0
PROGRAM_CHANGE = 0xC0
AFTER_TOUCH = 0xD0
PITCH_BEND = 0xE0
CONTROL_CHANGE = 0xB0

# Tuple of channel messages:

CHANNELS = (NOTE_ON, NOTE_OFF, POLY_AFTERTOUCH, PROGRAM_CHANGE, AFTER_TOUCH, PITCH_BEND, CONTROL_CHANGE)

# --== Real Time Messages: ==--

TIMING_CLOCK = 0xF8
START_SEQUENCE = 0xFA
CONTINUE_SEQUENCE = 0xFB
STOP_SEQUENCE = 0xFC
ACTIVE_SENSING = 0xFE
SYSTEM_RESET = 0xFF

REALTIME = (TIMING_CLOCK, START_SEQUENCE, CONTINUE_SEQUENCE, STOP_SEQUENCE, ACTIVE_SENSING, SYSTEM_RESET)

# --== System Exclusive Events: ==--

SYSTEM_EXCLUSIVE = 0xF0

EXCLUSIVE = [SYSTEM_EXCLUSIVE]

# --== System Common: ==--

SONG_POSITION_POINTER = 0xF2
SONG_SELECT = 0xF2
TUNE_REQUEST = 0xF6
EOX = 0xF7

SYSTEM_COMMON = [SONG_POSITION_POINTER, SONG_SELECT, TUNE_REQUEST, EOX]
